spring:
  application:
    name: springboot-developer

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:testdb

    h2:
      console:
        enabled: true
        path: /h2-console
        settings:
          web-allow-others: false
          trace: false
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password:
      driver-class-name: org.h2.Driver