version: '3.6'
services:
  postgres-dev:
    image: postgres:11
    container_name: postgres-dev
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: devdb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis-dev:
    image: redis:5
    container_name: redis-dev
    ports:
      - "16379:6379"